config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :posts
  resources :tasks

  root 'posts#index'

  resources :visitors do
    # resources :ideas
    # member do
    #   get '', to: 'visitors#index'
    #   # get                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    # end    
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def post_params
    #   params.require(:post).permit(:description, :image_one, :image_two)
    # end
end

app/views/visitors/index.html.erb
<table>
  <thead>
    <tr>
      <th>Description</th>
      <!--
      <th>Image one</th>
      <th>Image two</th>
      -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%#= post.image_one.filename %></td>
        <td><%#= post.image_two.filename %></td>
        <td><%= link_to 'Show', visitor_path(post) %></td>
        <td><%= link_to 'Edit', visitors_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visitors/show.html.erb
<%= form_for @post.idea do |form| %>

  <% if @post.idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @post.idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Post ID' %>
    <%= form.text_field :post_id, value: @post.id %>
  </div>

  <%#= @post.id %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, value: @post.idea.content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= form_for @post.task do |form| %>

  <% if @post.task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @post.task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label 'Post ID' %>
    <%= form.text_field :post_id, value: @post.id %>
  </div>

  <%#= @post.id %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_area :name, value: @post.task.name %>
  </div>


  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, value: @post.task.content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>