config/routes.rb
Rails.application.routes.draw do
  resources :ideas
  resources :posts
  resources :tasks

  root 'posts#index'

  resources :visitors do
    # resources :ideas
    # member do
    #   get '', to: 'visitors#index'
    #   # get                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    # end    
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  require 'open-uri'

  has_one :idea, foreign_key: "post_id", dependent: :destroy
  has_one :task, foreign_key: "post_id", dependent: :destroy  
  ## ACTIVE STORAGE CONFIGURATION
  has_one_attached :image_one
  has_one_attached :image_two
  has_one_attached :url_image

  # before_save :grab_image

  def grab_image(url)
    puts "RESULTADO => #{url}"
    # downloaded_image = open(url)
    # self.url_image.attach(io: downloaded_image, filename: "map.jpg", content_type:"image/jpg")
    # IO.copy_stream(download, self.url_image.attach(
    #   io:download_image, filename: "map.jpg", content_type:"image/jpg")
    # )
  end

end


# file_url = image[:image_url]
# download = open(file_url)
# IO.copy_stream(download,
# user.image.attach(
#   io: download,
#   filename: image[:name],
#   content_type: image[:content_type],
# ))

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        @idea = Idea.create(post_id: @post.id);
        @task = Task.create(post_id: @post.id);        
        @idea.save!
        @task.save!
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @posturl = params[:post][:url_image]
    # @post.grab_image(@posturl)
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description, :image_one, :image_two)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_one %>
    <%# if form.image_one.attached? %>
      <%#= image_tag(form.object.image_one) %>
      <%= form.file_field :image_one %>
    <%# else %>
      <%#= form.file_field :image_one %>
    <%# end %>
  </div>

  <div class="field">
    <%= form.label :image_two %>
    <%# if form.object.image_two %>
      <%#= image_tag(form.object.image_two) %>
      <%#= form.file_field :image_two %>
    <%# else %>
      <%= form.file_field :image_two %>
    <%# end %>
  </div>

  <div class="field">
    <%#= form.label :url_image %>
    <%#= form.text_area :url_image, placeholder:'Ingresar foto de mapa' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Image one</th>
      <th>Image two</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= post.image_one.filename %></td>
        <td><%= post.image_two.filename %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Image one:</strong>
  <%= image_tag(@post.image_one) %>
</p>

<p>
  <strong>Image two:</strong>
  <%= image_tag(@post.image_two) %>
</p>

<p>
  <strong>Url Image:</strong>
  <%#= image_tag(@post.url_image) %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= link_to 'Go to idea', edit_idea_path(@post) %>